export const PathUserApi = "localhost/user"
export const PathGetAllUsers = "/getAllUsers"
export const PathGetUser = "/getUser/"
export const PathUserDeleteCv = "/deleteCv/"
export const PathUserUpdateCv = "/updateCv/"

export const PathAdminApi = "/localhost/admin"
export const PathGetAllAdmins = "/getAllAdmins"
export const PathGetAdmin = "/getAdmin"
export const PathAdminAddAdmin = "/addAdmin"
export const PathAdminDeleteAdmin = "/deleteAdmin"
export const PathAdminUpdateAdmin = "/updateAdmin"
export const PathAdminFlagUser = "/flagUser/"

export const PathAdminDeleteUser = "/deleteCv"
