export const UserApi = "localhost/User"
export const UserAdd = "/addUser"
export const GetAllUsers = "/getAllUserAccounts"
export const GetUser = "/getIserAccount/{userId}"
export const UserDeleteCv = "/deleteUserAccount/{userId}"
export const UserUpdateCv = "/{userId}/{userName}/{password}"

export const AdminApi = "/localhost/AdminUser"
export const GetAllAdmins = "/getAllAdminAccounts"
export const GetAdmin = "/getAdminAccount/{adminId}"
export const AdminAddAdmin = "/addAdminUser"
export const AdminDeleteAdmin = "/deleteAdminAccount/{adminId}"
export const AdminUpdateAdmin = "/{adminId}/{adminUserName}/{password}"
export const AdminFlagUser = "/flagUser/"
export const AdminDeleteUser = "/deleteCv"

export const CommentApi = "/Comment"
export const CommentAdd = "/addComment"
export const GetAllComments = "/getAllComments"
export const GetComment = "/getComment/{commentId}"
export const UpdateComment = "/{commentId}/{adminId}/{userId}/{cvId}"
export const DeleteComment = "/deleteComment/{commentId}"

export const CvApi = "/CV"
export const CvAdd = "/uploadCV/{userId}"
export const CvGet = "/downloadFile/{cvId}"
export const CvDelete = "/deleteCV/{cvId}"
